version: '3.8'

services:

  db-estudiantes:
    image: postgres:15
    container_name: db-estudiantes
    environment:
      POSTGRES_DB: estudiantes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres -c max_prepared_transactions=100
    ports:
      - "5433:5432"

  db-examenes:
    image: postgres:15
    container_name: db-examenes
    environment:
      POSTGRES_DB: examenes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres -c max_prepared_transactions=100
    ports:
      - "5434:5432"

  wildfly:
    build: .
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - db-estudiantes
      - db-examenes